# Generated by Django 5.0.4 on 2024-05-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocked_subscriber',
            name='subscribed_to',
        ),
        migrations.RemoveField(
            model_name='blocked_subscriber',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribed_to',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='creator',
            new_name='content_creator',
        ),
        migrations.DeleteModel(
            name='Blocked_Subscriber',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
