# Generated by Django 5.0.4 on 2024-05-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_blocked_subscriber_subscribed_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
