# Generated by Django 5.0.4 on 2024-05-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_subscription_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(default='required', max_length=20),
        ),
    ]
